version: '3'

services:
  integracaodb:
    build: db
    container_name: integracao-db
    volumes:
      - integracao-volume:/var/lib/postgresql/data
    networks:
      - integracao-network
    env_file:
      - db/.env
    ports:
      - '5432:5432'
  integracaoapp:
    image: gleytonlima/gds-ephem-integracao
    container_name: integracao-app
    networks:
      - integracao-network
    env_file:
      - app/.env
    ports:
      - '8080:8080'

networks:
  integracao-network:
    ipam:
      driver: default
volumes:
  integracao-volume:
