version: '3'

services:
  integracaodb:
    build: docker/db
    container_name: integracao-db-development
    volumes:
      - integracao-volume:/var/lib/postgresql/data
    networks:
      - integracao-network-development
    env_file:
      - docker/db/.env
    ports:
      - '5432:5432'

networks:
  integracao-network-development:
    ipam:
      driver: default
volumes:
  integracao-volume:
