name: Build and Publish

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: app.jar
  SWAGGER_ARTIFACT_NAME: swagger.json
  DOCKER_IMAGE_NAME: gleytonlima/gds-ephem-integracao

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target/*.jar
          retention-days: 1
      - name: Archive Swagger
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SWAGGER_ARTIFACT_NAME }}
          path: target/*.json
          retention-days: 7
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
  docker:
    runs-on: ubuntu-latest
    environment: gds-ephem-integracao
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Retrieve saved app.jar
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target
      - name: Display structure of downloaded files
        run: ls -R
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .
          docker push ${{ env.DOCKER_IMAGE_NAME }}
      - name: restart app on digital ocean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd gds-vbe-api/
            docker-compose stop integracaoapp
            docker-compose pull integracaoapp
            docker-compose up -d integracaoapp
